-- Seeds the founding bibliography of the Shahryar Virtual Library.
--
-- These records are curated editorial content, so they ship with the schema
-- rather than being entered by hand after each deploy. ON CONFLICT DO NOTHING
-- keeps the migration safe to replay and lets the Foundation edit or remove any
-- row afterwards without this seed reasserting itself.

INSERT INTO "records" (
  "slug", "title_fa", "title_en", "cover_title_fa", "cover_title_en",
  "author_fa", "author_en", "summary_fa", "summary_en",
  "categories", "material_type", "date_label", "sort_year", "work_language",
  "publisher_fa", "publisher_en", "icon", "featured"
) VALUES
(
  'tarikh-i-bayhaqi',
  'تاریخ بیهقی (تاریخ مسعودی)',
  'Tārīkh-i Bayhaqī (The History of Masʿūd)',
  'تاریخ بیهقی',
  'Tārīkh-i Bayhaqī',
  'ابوالفضل محمد بن حسین بیهقی',
  'Abū al-Faḍl Muḥammad b. Ḥusayn Bayhaqī',
  'بخش بازمانده از تاریخی بزرگ که یکی از دبیران دیوان رسالت غزنویان نگاشته است. بیهقی رویدادهای دربار سلطان مسعود را با نگاه شاهد عینی روایت می‌کند و اثر او را قله نثر تاریخی پارسی می‌دانند.',
  'The surviving portion of a vast chronicle written by a secretary of the Ghaznavid chancery. Bayhaqī records the court of Sultan Masʿūd I as an eyewitness, and the work is regarded as the summit of Persian historical prose.',
  ARRAY['history-archaeology','literature-poetry'],
  'primary-source', 'c. 1059 CE', 1059, 'Persian', '', '', '📜', true
),
(
  'the-ghaznavids-bosworth',
  'غزنویان: امپراتوری آنان در افغانستان و شرق ایران (۹۹۴–۱۰۴۰)',
  'The Ghaznavids: Their Empire in Afghanistan and Eastern Iran, 994–1040',
  'غزنویان',
  'The Ghaznavids',
  'کلیفورد ادموند باسورث',
  'C. Edmund Bosworth',
  'پژوهش پایه و مرجع دربارهٔ برآمدن دولت غزنوی، سازمان دیوانی و سپاهی آن، و جایگاه غزنی به عنوان پایتخت یک امپراتوری. نقطهٔ آغاز هر پژوهش جدی در این زمینه.',
  'The foundational modern study of the rise of the Ghaznavid state, its chancery and army, and the standing of Ghazna as an imperial capital. The starting point for any serious research on the period.',
  ARRAY['history-archaeology'],
  'books-monographs', '1963', 1963, 'English',
  'انتشارات دانشگاه ادینبورگ', 'Edinburgh University Press', '🏛️', true
),
(
  'kitab-al-yamini',
  'کتاب الیمینی (تاریخ یمینی)',
  'Kitāb al-Yamīnī (The History of Maḥmūd)',
  'تاریخ یمینی',
  'Kitāb al-Yamīnī',
  'ابونصر محمد بن عبدالجبار عتبی',
  'Abū Naṣr Muḥammad al-ʿUtbī',
  'تاریخ رسمی و آراستهٔ دورهٔ سبکتگین و سلطان محمود به زبان عربی. متنی کلیدی برای شناخت تصویری که دربار غزنه از خود می‌ساخت.',
  'An ornate official history in Arabic of the reigns of Sebüktegin and Sultan Maḥmūd. A key text for understanding the image the Ghazna court constructed of itself.',
  ARRAY['history-archaeology','literature-poetry'],
  'primary-source', 'c. 1021 CE', 1021, 'Arabic', '', '', '🖋️', false
),
(
  'kufic-inscription-masud-iii',
  'کتیبهٔ کوفی به شعر پارسی در کاخ سلطنتی مسعود سوم در غزنی',
  'The Kūfic Inscription in Persian Verses in the Royal Palace of Masʿūd III at Ghazni',
  'کتیبه‌های کوفی',
  'Kūfic Inscription',
  'آلسیو بومباچی',
  'Alessio Bombaci',
  'خوانش و تحلیل کتیبهٔ سراسری کاخ مسعود سوم؛ سندی یگانه که نشان می‌دهد شعر پارسی در معماری رسمی غزنه چگونه به کار می‌رفت.',
  'The reading and analysis of the great frieze inscription of the palace of Masʿūd III — unique evidence for how Persian verse was deployed in the monumental architecture of Ghazna.',
  ARRAY['culture-heritage','history-archaeology'],
  'peer-reviewed-journal', '1966', 1966, 'English',
  'مؤسسهٔ ایتالیایی خاورمیانه و خاور دور', 'IsMEO, Rome', '🏺', false
),
(
  'islamic-metalwork-afghanistan',
  'فلزکاری اسلامی از افغانستان (سده‌های ۹ تا ۱۳ میلادی)',
  'Islamic Metalwork from Afghanistan (9th–13th Century)',
  'فلزکاری اسلامی',
  'Islamic Metalwork',
  'والنتینا لاویولا',
  'Valentina Laviola',
  'بررسی اشیای فلزی برآمده از کاوش‌های غزنی و پیرامون آن، با توجه به فن ساخت، تزیین و شبکه‌های بازرگانی که این آثار را جابه‌جا می‌کردند.',
  'A study of metal objects recovered from the excavations at Ghazni and its region, attentive to technique, ornament, and the trade networks that moved such pieces.',
  ARRAY['culture-heritage'],
  'peer-reviewed-journal', '2010s', 2015, 'English', '', '', '⚒️', false
),
(
  'zayn-al-akhbar',
  'زین‌الاخبار (تاریخ گردیزی)',
  'Zayn al-akhbār (The History of Gardīzī)',
  'زین‌الاخبار',
  'Zayn al-akhbār',
  'ابوسعید عبدالحی گردیزی',
  'Abū Saʿīd ʿAbd al-Ḥayy Gardīzī',
  'تاریخ عمومی به پارسی، نوشتهٔ نویسنده‌ای از گردیز؛ یکی از کهن‌ترین منابع بازمانده دربارهٔ خراسان و سال‌های نخست فرمانروایی غزنویان.',
  'A general history in Persian by an author from Gardīz — among the earliest surviving sources for Khurasan and the first Ghaznavid decades.',
  ARRAY['history-archaeology'],
  'primary-source', 'c. 1050 CE', 1050, 'Persian', '', '', '📖', false
),
(
  'later-ghaznavids-bosworth',
  'غزنویان متأخر: شکوه و زوال (۱۰۴۰–۱۱۸۶)',
  'The Later Ghaznavids: Splendour and Decay, 1040–1186',
  'غزنویان متأخر',
  'The Later Ghaznavids',
  'کلیفورد ادموند باسورث',
  'C. Edmund Bosworth',
  'ادامهٔ پژوهش باسورث؛ روایت سدهٔ پس از شکست دندانقان، جابه‌جایی مرکز قدرت به لاهور و واپسین دورهٔ فرهنگی غزنه.',
  'The sequel to the foundational study: the century after the defeat at Dandānqān, the shift of power toward Lahore, and the last cultural phase of Ghazna.',
  ARRAY['history-archaeology'],
  'books-monographs', '1977', 1977, 'English',
  'انتشارات دانشگاه ادینبورگ', 'Edinburgh University Press', '🏰', false
),
(
  'tabaqat-i-nasiri',
  'طبقات ناصری',
  'Ṭabaqāt-i Nāṣirī',
  'طبقات ناصری',
  'Ṭabaqāt-i Nāṣirī',
  'منهاج‌السراج جوزجانی',
  'Minhāj al-Sirāj Jūzjānī',
  'تاریخ عمومی اسلام تا حملهٔ مغول، با فصل‌هایی مبسوط دربارهٔ غزنویان و غوریان از قلم نویسنده‌ای که خود در این سرزمین‌ها زیسته بود.',
  'A general history of Islam down to the Mongol invasion, with substantial sections on the Ghaznavids and Ghurids by an author who lived in these lands.',
  ARRAY['history-archaeology'],
  'primary-source', 'c. 1260 CE', 1260, 'Persian', '', '', '📚', false
),
(
  'hudud-al-alam',
  'حدود العالم',
  'Ḥudūd al-ʿĀlam (The Regions of the World)',
  'حدود العالم',
  'Ḥudūd al-ʿĀlam',
  'مؤلف ناشناس؛ ترجمه و تحقیق ولادیمیر مینورسکی',
  'Anonymous; translated by V. Minorsky',
  'کهن‌ترین جغرافیای بازماندهٔ پارسی. توصیف آن از غزنه، راه‌ها و کالاهای بازرگانی، تصویری کم‌نظیر از اقتصاد منطقه پیش از اوج غزنویان می‌دهد.',
  'The oldest surviving geography in Persian. Its description of Ghazna, the roads, and the goods traded there gives a rare picture of the regional economy just before the Ghaznavid peak.',
  ARRAY['history-archaeology','economics-law'],
  'primary-source', '982 CE', 982, 'Persian', '', '', '🗺️', false
),
(
  'chahar-maqala',
  'چهار مقاله',
  'Chahār Maqāla (Four Discourses)',
  'چهار مقاله',
  'Chahār Maqāla',
  'نظامی عروضی سمرقندی',
  'Niẓāmī ʿArūḍī Samarqandī',
  'مجموعه‌ای از حکایت‌ها دربارهٔ دبیران، شاعران، ستاره‌شماران و پزشکان. مهم‌ترین گزارش‌های کهن دربارهٔ شاعران دربار غزنه، از جمله فردوسی، در همین کتاب آمده است.',
  'A collection of anecdotes on secretaries, poets, astrologers, and physicians. It preserves the most important early accounts of the poets of the Ghazna court, Firdawsī among them.',
  ARRAY['literature-poetry'],
  'primary-source', 'c. 1156 CE', 1156, 'Persian', '', '', '🪶', false
),
(
  'tahqiq-ma-li-l-hind',
  'تحقیق ما للهند (کتاب الهند)',
  'Taḥqīq mā li-l-Hind (The Book of India)',
  'کتاب الهند',
  'Book of India',
  'ابوریحان بیرونی',
  'Abū Rayḥān al-Bīrūnī',
  'پژوهشی سنجیده دربارهٔ دانش، دین و گاه‌شماری هند که در قلمرو غزنویان نگاشته شد؛ نمونه‌ای درخشان از روش علمی و مدارای فرهنگی در سدهٔ پنجم.',
  'A measured study of Indian learning, religion, and chronology, written within the Ghaznavid domain — a landmark of scientific method and cultural openness in the eleventh century.',
  ARRAY['history-archaeology','culture-heritage'],
  'primary-source', 'c. 1030 CE', 1030, 'Arabic', '', '', '🔬', true
),
(
  'hadiqat-al-haqiqa',
  'حدیقة الحقیقة و شریعة الطریقة',
  'Ḥadīqat al-Ḥaqīqa (The Walled Garden of Truth)',
  'حدیقة الحقیقة',
  'Ḥadīqat al-Ḥaqīqa',
  'حکیم سنایی غزنوی',
  'Ḥakīm Sanāʾī of Ghazna',
  'نخستین منظومهٔ بزرگ عرفانی در زبان پارسی، سرودهٔ شاعری که زادهٔ غزنه بود و در همان شهر آرام گرفت. سنایی راه را برای عطار و مولوی گشود.',
  'The first great mystical poem in Persian, by a poet born in Ghazna and buried there. Sanāʾī opened the road later travelled by ʿAṭṭār and Rūmī.',
  ARRAY['literature-poetry'],
  'primary-source', 'c. 1131 CE', 1131, 'Persian', '', '', '🌿', true
),
(
  'divan-farrukhi-sistani',
  'دیوان فرخی سیستانی',
  'Dīwān of Farrukhī Sīstānī',
  'دیوان فرخی',
  'Dīwān of Farrukhī',
  'فرخی سیستانی',
  'Farrukhī Sīstānī',
  'قصیده‌های شاعر دربار محمود و مسعود. وصف‌های او از اردوکشی‌ها، جشن‌ها و منظرهٔ غزنه از زنده‌ترین گزارش‌های شاعرانهٔ آن روزگار است.',
  'The odes of a poet at the courts of Maḥmūd and Masʿūd. His descriptions of campaigns, festivals, and the landscape of Ghazna are among the most vivid poetic reportage of the age.',
  ARRAY['literature-poetry'],
  'primary-source', '11th century CE', 1035, 'Persian', '', '', '🎼', false
),
(
  'divan-unsuri',
  'دیوان عنصری بلخی',
  'Dīwān of ʿUnṣurī Balkhī',
  'دیوان عنصری',
  'Dīwān of ʿUnṣurī',
  'ابوالقاسم حسن عنصری بلخی',
  'Abū al-Qāsim Ḥasan ʿUnṣurī Balkhī',
  'سرودهٔ ملک‌الشعرای دربار سلطان محمود. آنچه بازمانده، اندک است اما جایگاه او را در شکل‌گیری قصیدهٔ درباری پارسی نشان می‌دهد.',
  'The work of the poet laureate at the court of Sultan Maḥmūd. Little survives, but enough to show his part in shaping the Persian courtly ode.',
  ARRAY['literature-poetry'],
  'primary-source', '11th century CE', 1030, 'Persian', '', '', '👑', false
),
(
  'shahnama-firdawsi',
  'شاهنامه',
  'Shāhnāma (The Book of Kings)',
  'شاهنامه',
  'Shāhnāma',
  'ابوالقاسم فردوسی',
  'Abū al-Qāsim Firdawsī',
  'حماسهٔ ملی ایران و پارسی‌زبانان، که به سلطان محمود غزنوی تقدیم شد. پیوند دشوار و پرماجرای شاعر با دربار غزنه، خود بخشی از تاریخ فرهنگی این شهر است.',
  'The national epic of the Persian-speaking world, dedicated to Sultan Maḥmūd of Ghazna. The difficult, much-debated relationship between poet and court is itself part of the cultural history of the city.',
  ARRAY['literature-poetry','culture-heritage'],
  'primary-source', 'c. 1010 CE', 1010, 'Persian', '', '', '🐉', true
),
(
  'siyasatnama',
  'سیاست‌نامه (سیر الملوک)',
  'Siyāsatnāma (Siyar al-Mulūk)',
  'سیاست‌نامه',
  'Siyāsatnāma',
  'خواجه نظام‌الملک طوسی',
  'Niẓām al-Mulk Ṭūsī',
  'راهنمای فرمانروایی و دیوان‌داری از وزیر سلجوقی. حکایت‌های آن دربارهٔ مالیات، دادخواهی و آیین دربار غزنویان از منابع دست اول تاریخ اداری و حقوقی منطقه است.',
  'A manual of governance and administration by the Seljuk vizier. Its anecdotes on taxation, petitions, and Ghaznavid court practice are primary evidence for the administrative and legal history of the region.',
  ARRAY['economics-law'],
  'primary-source', 'c. 1091 CE', 1091, 'Persian', '', '', '⚖️', false
),
(
  'turkestan-mongol-invasion',
  'ترکستان‌نامه تا حملهٔ مغول',
  'Turkestan Down to the Mongol Invasion',
  'ترکستان‌نامه',
  'Turkestan',
  'واسیلی ولادیمیروویچ بارتولد',
  'V. V. Barthold',
  'پژوهش کلاسیک دربارهٔ آسیای میانه و خراسان که چارچوب مطالعهٔ اقتصاد، زمین‌داری و ساخت سیاسی این منطقه را برای یک سده پایه گذاشت.',
  'The classic study of Central Asia and Khurasan, which set the framework for a century of work on the economy, landholding, and political structure of the region.',
  ARRAY['history-archaeology','economics-law'],
  'books-monographs', '1928 (English edition)', 1928, 'Russian / English',
  'انجمن آسیایی سلطنتی', 'Royal Asiatic Society', '🌏', false
),
(
  'ghaznavid-military-organisation',
  'سازمان سپاهی غزنویان',
  'Ghaznevid Military Organisation',
  'سازمان سپاهی',
  'Military Organisation',
  'کلیفورد ادموند باسورث',
  'C. Edmund Bosworth',
  'تحلیل ساختار سپاه غزنوی: غلامان، سواران ترک، فیل‌ها و هزینهٔ نگاه‌داشت آن. مقاله‌ای که پیوند میان توان نظامی و فشار مالی را روشن می‌کند.',
  'An analysis of the Ghaznavid army — slave soldiers, Turkish cavalry, elephants, and the cost of maintaining them. The article makes plain the link between military reach and fiscal strain.',
  ARRAY['economics-law','history-archaeology'],
  'peer-reviewed-journal', 'Der Islam 36 (1960)', 1960, 'English', '', 'Der Islam', '🛡️', false
),
(
  'imperial-policy-early-ghaznawids',
  'سیاست امپراتوری در دورهٔ نخست غزنویان',
  'The Imperial Policy of the Early Ghaznawids',
  'سیاست امپراتوری',
  'Imperial Policy',
  'کلیفورد ادموند باسورث',
  'C. Edmund Bosworth',
  'بررسی انگیزه‌های لشکرکشی، غنیمت و مشروعیت‌سازی خلافتی در دههٔ‌های آغازین دولت غزنوی.',
  'An examination of the motives behind campaigning, plunder, and the search for caliphal legitimacy in the opening decades of the Ghaznavid state.',
  ARRAY['economics-law','history-archaeology'],
  'peer-reviewed-journal', 'Islamic Studies 1 (1962)', 1962, 'English', '', 'Islamic Studies', '📊', false
),
(
  'ghazni-funerary-inscriptions',
  'سنگ‌نوشته‌های گورستانی غزنی',
  'The Funerary Inscriptions of Ghazni',
  'سنگ‌نوشته‌ها',
  'Funerary Inscriptions',
  'روبرتا جونتا',
  'Roberta Giunta',
  'گردآوری و خوانش سنگ‌نوشته‌های آرامگاهی غزنی از سدهٔ چهارم تا نهم هجری؛ پیکره‌ای که نام‌ها، القاب و پیشه‌های ساکنان شهر را بازمی‌گوید.',
  'The corpus and reading of the funerary inscriptions of Ghazni from the tenth to the fifteenth century — a body of evidence that returns the names, titles, and trades of the inhabitants of the city.',
  ARRAY['culture-heritage'],
  'peer-reviewed-journal', '2003', 2003, 'French', '', 'Naples, Università degli Studi di Napoli', '🪦', false
),
(
  'masud-iii-palace-excavations',
  'کاوش‌های باستان‌شناسی در غزنی و کاخ مسعود سوم',
  'Excavations at Ghazni and the Palace of Masʿūd III',
  'کاوش‌های غزنی',
  'Excavations at Ghazni',
  'اومبرتو شراتو و هیئت باستان‌شناسی ایتالیا',
  'Umberto Scerrato and the Italian Archaeological Mission',
  'گزارش‌های کاوش کاخ مسعود سوم و محوطه‌های پیرامون، که نقشهٔ معماری، تزیینات مرمرین و لایه‌های شهری غزنهٔ غزنوی را آشکار کرد.',
  'The excavation reports on the palace of Masʿūd III and its surrounding sites, which revealed the architectural plan, the carved marble revetments, and the urban stratigraphy of Ghaznavid Ghazna.',
  ARRAY['history-archaeology','culture-heritage'],
  'peer-reviewed-journal', 'from 1957 onward', 1957, 'English / Italian', '', 'East and West, IsMEO', '⛏️', false
),
(
  'minarets-of-ghazni',
  'مناره‌های غزنی: مستندسازی و پاسداشت',
  'The Minarets of Ghazni: Documentation and Conservation',
  'مناره‌های غزنی',
  'Minarets of Ghazni',
  'هیئت باستان‌شناسی ایتالیا در افغانستان و همکاران',
  'Italian Archaeological Mission in Afghanistan and collaborators',
  'مطالعات مربوط به دو منارهٔ برجای‌ماندهٔ مسعود سوم و بهرام‌شاه؛ نقش‌های آجری، کتیبه‌ها و مسئلهٔ دشوار نگاه‌داری آنها.',
  'Studies of the two surviving minarets of Masʿūd III and Bahrām Shāh — their brick patterning, their inscriptions, and the hard problem of keeping them standing.',
  ARRAY['culture-heritage','history-archaeology'],
  'peer-reviewed-journal', '20th–21st century', 2000, 'English / Italian', '', '', '🕌', false
),
(
  'encyclopaedia-iranica-ghazna',
  'مدخل‌های «غزنه» و «غزنویان» در دانشنامهٔ ایرانیکا',
  'Ghazna and Ghaznavids — Encyclopaedia Iranica',
  'ایرانیکا',
  'Encyclopaedia Iranica',
  'کلیفورد ادموند باسورث و دیگران',
  'C. Edmund Bosworth and others',
  'مدخل‌های مرجع و کتاب‌شناسی‌های همراه آنها؛ سریع‌ترین راه برای یافتن منابع معتبر دربارهٔ شهر، دودمان و فرهنگ غزنه.',
  'Reference entries and the bibliographies attached to them — the fastest route into the reliable literature on the city, the dynasty, and the culture of Ghazna.',
  ARRAY['history-archaeology','culture-heritage'],
  'books-monographs', 'from 1982 onward', 1982, 'English', '', 'Encyclopaedia Iranica Foundation', '🔖', false
),
(
  'afghanistan-cultural-political-history',
  'افغانستان: تاریخ فرهنگی و سیاسی',
  'Afghanistan: A Cultural and Political History',
  'تاریخ افغانستان',
  'A Cultural and Political History',
  'توماس بارفیلد',
  'Thomas Barfield',
  'زمینهٔ بلندمدت: چگونگی پیوند ساخت‌های قومی، اقتصادی و حقوقی در سرزمینی که غزنی یکی از کانون‌های تاریخی آن است.',
  'The long view: how ethnic, economic, and legal structures have interlocked across the country of which Ghazni is one of the historic centres.',
  ARRAY['culture-heritage','economics-law'],
  'books-monographs', '2010', 2010, 'English',
  'انتشارات دانشگاه پرینستون', 'Princeton University Press', '🧭', false
)
ON CONFLICT ("slug") DO NOTHING;
